services:
  - mysql
language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
before_install:
  - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``
env:
  - CI_JOB=lint_syntax
  - CI_JOB=build_test
  - CI_JOB=lint_style
matrix:
  exclude:
    - php: '7.2'
      env: CI_JOB=lint_style
    - php: '7.3'
      env: CI_JOB=lint_style
before_script: echo 'error_reporting = "E_ALL & ~E_NOTICE & ~E_STRICT"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - bash ci/ci.sh --dir ./
