name: Build and test - PHP 7.3 - Apache - MariaDB 10.5

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-20.04
        name: Run build and test - PHP 7.3 - Apache - MariaDB 10.5
        steps:
            - uses: actions/checkout@v2

            - name: Install npm package
              uses: actions/setup-node@v1
              with:
                node-version: '12'

            - name: Include ci bash library
              run: source ci/ciLibrary.source

            - name: Dockers environment start
              run: dockers_env_start

            - name: Composer github authentication
              run: composer_github_auth

            - name: Main build
              run: main_build

            - name: CCDA build
              run: ccda_build

            - name: Install and configure
              run: install_configure

            - name: Unit testing
              run: build_test_unit

            - name: E2e testing
              run: build_test_e2e

            - name: Api testing
              run: build_test_api

            - name: Fixtures testing
              run: build_test_fixtures

            - name: Services testing
              run: build_test_services

            - name: Validators testing
              run: build_test_validators

            - name: Controllers testing
              run: build_test_controllers

            - name: Common testing
              run: build_test_common
