name: PHP Styling

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Check PHP Styling
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Report PHP Version
        run: php -v

      - name: Check PHP Styling
        run: |
          failTest=false
          composer global require "squizlabs/php_codesniffer=3.*" || failTest=true
          $HOME/.composer/vendor/bin/phpcs -p -n --extensions=php,inc --report-width=120 --standard=ci/phpcs.xml --report=full . || failTest=true
          if $failTest; then
            exit 1
          fi
